import type { Article, Reel, Author } from './types';

export const defaultAuthors: Author[] = [
  {
    _id: 'redaccion-diaspora',
    name: 'Redacción Diáspora',
    slug: 'redaccion-diaspora',
    bio: 'Equipo editorial especializado en noticias internacionales y comunidades hispanas.',
    avatarUrl: '/images/hero_summit.jpg',
    role: 'Editorial',
    socialLinks: {
      twitter: 'https://twitter.com',
      website: 'https://eldiariodeladiaspora.com',
    },
  },
];

export const defaultReels: Reel[] = [
  {
    _id: 'reel-1',
    title: 'Resumen de la Cumbre Internacional de la Diáspora en 60 segundos',
    url: 'https://www.youtube.com',
    createdAt: '2026-09-03T12:00:00Z',
  },
  {
    _id: 'reel-2',
    title: 'Así funciona el nuevo pasaporte biométrico dominicano',
    url: 'https://www.youtube.com',
    createdAt: '2026-09-03T11:00:00Z',
  },
  {
    _id: 'reel-3',
    title: 'Lo mejor del Festival de Culturas de la Diáspora',
    url: 'https://www.youtube.com',
    createdAt: '2026-09-03T10:00:00Z',
  },
];

export const defaultArticles: Article[] = [
  {
    _id: 'cumbre-iberoamericana-diaspora-2026',
    title: 'Cumbre Internacional de la Diáspora: Líderes globales aprueban histórico pacto de integración y derechos migratorios',
    slug: 'cumbre-iberoamericana-diaspora-2026',
    summary: 'Delegaciones de más de 25 naciones firman en Madrid un acuerdo sin precedentes para agilizar la homologación de títulos, facilitar la inversión productiva de remesas y proteger a los trabajadores en el exterior.',
    content: '<p>En una jornada calificada como histórica por analistas y diplomáticos, mandatarios y representantes de las principales comunidades en el exterior cerraron hoy la Cumbre Internacional de la Diáspora con la firma del Tratado Global de Movilidad y Protección Migratoria.</p><p>El documento ratifica compromisos multilaterales para reducir sustancialmente los costes de envío de remesas, blindar los derechos laborales de los trabajadores migrantes e instaurar ventanillas únicas de homologación universitaria.</p>',
    categoryId: 'la-diaspora',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/hero_summit.jpg',
    thumbnailUrl: '/images/hero_summit.jpg',
    status: 'published',
    publishedAt: '2026-09-03T14:30:00Z',
    updatedAt: '2026-09-03T14:30:00Z',
    createdAt: '2026-09-03T12:00:00Z',
    readingTimeMinutes: 5,
    tags: ['cumbre', 'diaspora', 'internacional', 'derechos'],
    allowComments: true,
    isMainHero: true,
    heroOrder: 1,
    showOnMostRead: false,
  },
  {
    _id: 'inteligencia-artificial-salud-innovacion-hispana',
    title: 'Científicos e ingenieros hispanos revolucionan el diagnóstico médico con nueva plataforma de IA',
    slug: 'inteligencia-artificial-salud-innovacion-hispana',
    summary: 'Un equipo multidisciplinario liderado por talento latino en Europa y EE.UU. presenta NeuroDiagnostix, un sistema capaz de detectar anomalías neurológicas con precisión récord.',
    content: '<p>La innovación tecnológica impulsada por la comunidad de la diáspora continúa marcando pauta en los principales foros científicos mundiales. El congreso anual de tecnología sanitaria fue testigo de la presentación de un modelo de inteligencia artificial de código abierto desarrollado para acelerar diagnósticos clínicos tempranos.</p>',
    categoryId: 'actualidad',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/actualidad_tech.jpg',
    thumbnailUrl: '/images/actualidad_tech.jpg',
    status: 'published',
    publishedAt: '2026-09-03T13:45:00Z',
    updatedAt: '2026-09-03T13:45:00Z',
    createdAt: '2026-09-03T11:00:00Z',
    readingTimeMinutes: 4,
    tags: ['tecnologia', 'salud', 'inteligencia artificial'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: true,
    mostReadOrder: 1,
  },
  {
    _id: 'emprendedores-latinos-expansion-global-records',
    title: 'El auge del emprendimiento latino: Empresas fundadas por la diáspora superan los 50.000 empleos',
    slug: 'emprendedores-latinos-expansion-global-records',
    summary: 'Nuevos fondos de capital de riesgo y redes de mentoría impulsan la expansión de startups fundadas por inmigrantes en Nueva York, Ciudad de México, Madrid y Bogotá.',
    content: '<p>El ecosistema empresarial fundado por emprendedores de la diáspora vive un momento estelar. Informes recientes confirman que la inversión canalizada a través de fondos liderados por latinos ha alcanzado cifras récord en el último trimestre, dinamizando la creación de empleo cualificado.</p>',
    categoryId: 'la-diaspora',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/diaspora_entrepreneurs.jpg',
    thumbnailUrl: '/images/diaspora_entrepreneurs.jpg',
    status: 'published',
    publishedAt: '2026-09-03T12:30:00Z',
    updatedAt: '2026-09-03T12:30:00Z',
    createdAt: '2026-09-03T10:00:00Z',
    readingTimeMinutes: 4,
    tags: ['emprendimiento', 'negocios', 'diaspora'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: true,
    mostReadOrder: 2,
  },
  {
    _id: 'republica-dominicana-pasaporte-biometrico-digital',
    title: 'República Dominicana estrena moderna red consular con emisión inmediata de pasaportes biométricos',
    slug: 'republica-dominicana-pasaporte-biometrico-digital',
    summary: 'El nuevo sistema digital reduce tiempos de espera de meses a pocas horas en las sedes consulares internacionales de Santo Domingo, Nueva York, Miami y Madrid.',
    content: '<p>En un esfuerzo integral de digitalización gubernamental, la Cancillería y la Dirección General de Pasaportes han puesto en marcha el sistema biométrico de última generación para todos los ciudadanos residentes tanto en el país como en el extranjero.</p>',
    categoryId: 'nacional',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/nacional_consulado.jpg',
    thumbnailUrl: '/images/nacional_consulado.jpg',
    status: 'published',
    publishedAt: '2026-09-03T11:15:00Z',
    updatedAt: '2026-09-03T11:15:00Z',
    createdAt: '2026-09-03T09:00:00Z',
    readingTimeMinutes: 3,
    tags: ['consulado', 'pasaportes', 'republica dominicana'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: true,
    mostReadOrder: 3,
  },
  {
    _id: 'acuerdo-historico-cooperacion-america-latina-europa',
    title: 'Histórico acuerdo de cooperación comercial y movilidad académica entre América Latina y Europa',
    slug: 'acuerdo-historico-cooperacion-america-latina-europa',
    summary: 'Ministros de Relaciones Exteriores firman un tratado multilateral que abre miles de becas y exonera aranceles a productos de economías emergentes.',
    content: '<p>Con la presencia de delegaciones de alto nivel, se formalizó hoy el pacto que garantizará intercambios universitarios directos y la simplificación aduanera para pymes exportadoras de la región.</p>',
    categoryId: 'internacional',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/internacional_acuerdo.jpg',
    thumbnailUrl: '/images/internacional_acuerdo.jpg',
    status: 'published',
    publishedAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-03T10:00:00Z',
    createdAt: '2026-09-03T08:00:00Z',
    readingTimeMinutes: 4,
    tags: ['diplomacia', 'comercio', 'acuerdo internacional'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: false,
  },
  {
    _id: 'remesas-fintech-revolucion-ahorro-comisiones',
    title: 'El impacto de las Fintech en las remesas: Comisiones bajan un 60% gracias a nuevas plataformas móviles',
    slug: 'remesas-fintech-revolucion-ahorro-comisiones',
    summary: 'Millones de familias en el Caribe y América Latina reciben fondos al instante mediante transferencias digitales directas, dinamizando el comercio local.',
    content: '<p>La adopción masiva de herramientas financieras móviles ha transformado la forma en que los migrantes apoyan a sus familias en origen, recortando costes intermediarios y bancarizando a miles de personas.</p>',
    categoryId: 'economia',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/economia_remesas.jpg',
    thumbnailUrl: '/images/economia_remesas.jpg',
    status: 'published',
    publishedAt: '2026-09-03T09:00:00Z',
    updatedAt: '2026-09-03T09:00:00Z',
    createdAt: '2026-09-03T07:00:00Z',
    readingTimeMinutes: 4,
    tags: ['remesas', 'fintech', 'economia'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: true,
    mostReadOrder: 4,
  },
  {
    _id: 'beisbol-estrellas-latinas-grandes-ligas-hazaña',
    title: 'Noche gloriosa en las Grandes Ligas: Estrellas dominicanas y latinas comandan la tabla con marcas históricas',
    slug: 'beisbol-estrellas-latinas-grandes-ligas-hazaña',
    summary: 'Con estadio lleno y ovación de pie, los bateadores caribeños definen los playoffs con jonrones decisivos en el noveno episodio.',
    content: '<p>Una velada para el recuerdo en el béisbol profesional estadounidense. Los representantes dominicanos y latinoamericanos volvieron a demostrar su calibre legendario con actuaciones estelares que sellaron el pase a la postemporada.</p>',
    categoryId: 'deportes',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/deportes_baseball.jpg',
    thumbnailUrl: '/images/deportes_baseball.jpg',
    status: 'published',
    publishedAt: '2026-09-03T08:00:00Z',
    updatedAt: '2026-09-03T08:00:00Z',
    createdAt: '2026-09-03T06:00:00Z',
    readingTimeMinutes: 3,
    tags: ['deportes', 'beisbol', 'grandes ligas'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: false,
  },
  {
    _id: 'festival-internacional-culturas-diaspora-madrid-ny',
    title: 'Festival Internacional de las Culturas reúne a más de 100.000 asistentes en un tributo a las tradiciones migrantes',
    slug: 'festival-internacional-culturas-diaspora-madrid-ny',
    summary: 'Música en vivo, gastronomía caribeña y danzas folclóricas llenan las avenidas de color y hermanamiento intercontinental.',
    content: '<p>El festival multitudinario congregó a miles de familias en una auténtica fiesta de música y gastronomía, celebrando la rica herencia cultural de la diáspora en las principales capitales del mundo.</p>',
    categoryId: 'cultura',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/cultura_festival.jpg',
    thumbnailUrl: '/images/cultura_festival.jpg',
    status: 'published',
    publishedAt: '2026-09-03T07:00:00Z',
    updatedAt: '2026-09-03T07:00:00Z',
    createdAt: '2026-09-03T05:00:00Z',
    readingTimeMinutes: 3,
    tags: ['cultura', 'festival', 'musica', 'diaspora'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: false,
  },
  {
    _id: 'redes-apoyo-comunitario-salud-educacion-familias',
    title: 'Centros comunitarios amplían programas de salud preventiva y becas universitarias para hijos de inmigrantes',
    slug: 'redes-apoyo-comunitario-salud-educacion-familias',
    summary: 'Organizaciones barriales coordinan recursos médicos y talleres de orientación académica en favor de miles de familias de la diáspora.',
    content: '<p>La solidaridad vecinal y el trabajo en red vuelven a marcar la diferencia. Diversas asociaciones comunitarias han anunciado la ampliación de sus fondos de apoyo para cubrir atención médica primaria y tutorías académicas gratuitas.</p>',
    categoryId: 'la-comunidad',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/comunidad_apoyo.jpg',
    thumbnailUrl: '/images/comunidad_apoyo.jpg',
    status: 'published',
    publishedAt: '2026-09-03T06:00:00Z',
    updatedAt: '2026-09-03T06:00:00Z',
    createdAt: '2026-09-03T04:00:00Z',
    readingTimeMinutes: 4,
    tags: ['comunidad', 'salud', 'educacion', 'familias'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: false,
  },
  {
    _id: 'editorial-puentes-humanos-construyendo-futuro',
    title: 'Editorial: La diáspora no solo envía dinero, exporta esperanza, cultura y liderazgo al mundo',
    slug: 'editorial-puentes-humanos-construyendo-futuro',
    summary: 'Una reflexión profunda sobre el rol protagónico que desempeñan las comunidades emigrantes en el desarrollo de sus países de origen y de acogida.',
    content: '<p>Durante generaciones, la narrativa sobre la migración se redujo a cifras macroeconómicas y transferencias monetarias. Sin embargo, la mayor riqueza de la diáspora reside en su capital humano: su resiliencia, su talento y su capacidad de construir puentes de progreso mutuo.</p>',
    categoryId: 'opinion',
    subCategoryId: null,
    authorId: 'redaccion-diaspora',
    heroImageUrl: '/images/opinion_editorial.jpg',
    thumbnailUrl: '/images/opinion_editorial.jpg',
    status: 'published',
    publishedAt: '2026-09-03T05:00:00Z',
    updatedAt: '2026-09-03T05:00:00Z',
    createdAt: '2026-09-03T03:00:00Z',
    readingTimeMinutes: 5,
    tags: ['editorial', 'opinion', 'diaspora', 'liderazgo'],
    allowComments: true,
    isMainHero: false,
    showOnMostRead: false,
  },
]
